app = 'aliyaassistent-bot-vfjd2w'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  PORT = "8080"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
